const file=document.getElementById("file"),drop=document.getElementById("drop"),browse=document.getElementById("browse"),dropContent=document.getElementById("dropContent"),previewWrap=document.getElementById("previewWrap"),preview=document.getElementById("preview"),analyze=document.getElementById("analyze"),clearBtn=document.getElementById("clearBtn"),idle=document.getElementById("idle"),loading=document.getElementById("loading"),output=document.getElementById("output"),scan=document.getElementById("scan"),model=document.getElementById("model"),heat=document.getElementById("heat");
let currentUrl=null;
browse.addEventListener("click",e=>{e.stopPropagation();file.click()});
drop.addEventListener("click",()=>{if(dropContent.classList.contains("hidden"))return;file.click()});
file.addEventListener("change",e=>load(e.target.files[0]));
["dragenter","dragover"].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add("drag")}));
["dragleave","drop"].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove("drag")}));
drop.addEventListener("drop",e=>load(e.dataTransfer.files[0]));
function load(f){if(!f||!f.type.startsWith("image/"))return;if(currentUrl)URL.revokeObjectURL(currentUrl);currentUrl=URL.createObjectURL(f);preview.src=currentUrl;heat.src=currentUrl;dropContent.classList.add("hidden");previewWrap.classList.remove("hidden");analyze.disabled=false;clearBtn.classList.remove("hidden");idle.classList.remove("hidden");output.classList.add("hidden");loading.classList.add("hidden")}
clearBtn.addEventListener("click",()=>{file.value="";dropContent.classList.remove("hidden");previewWrap.classList.add("hidden");analyze.disabled=true;clearBtn.classList.add("hidden");output.classList.add("hidden");loading.classList.add("hidden");idle.classList.remove("hidden")});
const demo={EfficientNetB0:{name:"Melanocytic Nevi",code:"NV",conf:88.7,vals:[["Melanocytic Nevi",88.7],["Melanoma",5.4],["Basal Cell Carcinoma",3.2],["Benign Keratosis",2.7]]},ResNet50:{name:"Melanocytic Nevi",code:"NV",conf:84.9,vals:[["Melanocytic Nevi",84.9],["Melanoma",7.1],["Basal Cell Carcinoma",4.8],["Benign Keratosis",3.2]]},"Custom CNN":{name:"Melanocytic Nevi",code:"NV",conf:81.6,vals:[["Melanocytic Nevi",81.6],["Melanoma",8.8],["Basal Cell Carcinoma",5.5],["Benign Keratosis",4.1]]}};
analyze.addEventListener("click",()=>{loading.classList.remove("hidden");idle.classList.add("hidden");output.classList.add("hidden");scan.classList.remove("hidden");setTimeout(()=>{const d=demo[model.value];document.getElementById("predName").textContent=d.name;document.getElementById("predCode").textContent=d.code+" · simulated demo output";document.getElementById("conf").textContent=d.conf.toFixed(1)+"%";document.getElementById("modelName").textContent=model.value;document.getElementById("bars").innerHTML=d.vals.map(v=>`<div class="bar"><div class="bar-top"><span>${v[0]}</span><span>${v[1].toFixed(1)}%</span></div><div class="track"><div class="fill" style="width:${v[1]}%"></div></div></div>`).join("");loading.classList.add("hidden");scan.classList.add("hidden");output.classList.remove("hidden")},1400)});
